spring.application.name=pro2

langchain4j.open-ai.chat-model.api-key=${OPEN_AI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=dokk
spring.datasource.password=dokkeabi
spring.datasource.driver-class-name=org.postgresql.Driver
