spring.application.name=pro2

langchain4j.open-ai.chat-model.api-key=${OPEN_AI_API_KEY}

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework=DEBUG